### ISSUE TITLE
SystemError: <built-in function delete_Status> returned a result with an error set

### ISSUE THREAD

**Issue by Waffleboy** [eldor4do/Tensorflow-Examples#3]
When i run the default example for retraining-example.py, i get this error. model is trained, and output files are specified correctly

More detail: executing file NOT In the tensorflow main directory as then import tensorflow as tf doesnt work and throws a pywrap error

**Comment by unography** [comment]
I'm sorry but could you expand on your error a bit? I couldn't quite understand it.

**Comment by Waffleboy** [comment]
Hey eldor, thanks for your quick reply!

I've outlined it here:

http://stackoverflow.com/questions/38080620/tensorflow-image-retraining-has-systemerror-built-in-function-delete-status-re

thank you!

**Comment by Waffleboy** [comment]
Hi, is there any update on this issue? :) 

Some additional information: the error occurs when i run the 

```
predictions = sess.run(softmax_tensor,
                               {'DecodeJpeg/contents:0': image_data})
```

line.

**Comment by unography** [comment]
@Waffleboy Hi, I'm sorry I couldn't yet find a solution to this. You could try asking on the main tensorflow page? The code is mostly taken from the default imagenet example.

**Comment by RedTachyon** [comment]
https://github.com/tensorflow/tensorflow/issues/3002
Basically, you have to install TF version 0.9.0rc0 and do everything from the beginning (build the network, retrain)

**Comment by chulgs15** [comment]
Hello Waffleboy

I hope my opinion help you.
I experience same problem. but now I solve my problem.

In my case, The retrained model by "bazel-bin" cannot run eldor4do 's python script.
( Sorry, I do not now why... )

try retrain model by "/tensorflow/examples/image_retraining/retrain.py". and then, run eldor4do 's python script.

maybe it works.

thank you.
